import {AUTOMATION_TASK_IDS} from './task-purpose.mjs';
export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const messages={MARKET_SESSION_REQUIRED:'登录已失效，请重新登录。',MARKET_IDEMPOTENCY_CONFLICT:'这次创建请求已登记，请刷新任务列表核对。',MARKET_ACCESS_DENIED:'任务不存在或无权访问。',MARKET_INPUT_INVALID:'请检查任务名称、国家和关键词。',MARKET_COUNTRY_LIMIT:'每个任务请选择1–3个国家。',MARKET_COUNTRY_DUPLICATE:'同一国家只能添加一次。',MARKET_KEYWORD_DUPLICATE:'同一国家的关键词不能重复。',MARKET_KEYWORD_INVALID:'每个关键词需要1–100个字符。'};
export function friendly(e){const code=String(e?.message||'');for(const [key,value] of Object.entries(messages))if(code.includes(key))return value;if(e?.code==='PGRST205'||e?.code==='PGRST202'||e?.code==='42P01')return '任务服务尚未就绪，请稍后刷新。';return '请求未完成，请检查网络后重试。原任务不会因此被删除。';}
export function validate(name,sites){if(!name.trim()||[...name.trim()].length>80)throw Error('任务名称需要1–80个字符。');if(!sites.length||sites.length>3)throw Error('每个任务请选择1–3个国家。');const countries=new Set();for(const s of sites){if(!/^[A-Z]{2}$/.test(s.country)||countries.has(s.country))throw Error('请选择不重复的国家。');countries.add(s.country);if(!s.keywords.length||s.keywords.length>3||s.keywords.some(k=>![...k.trim()].length||[...k].length>100))throw Error('每个国家填写1–3个ABA品名词，每词不超过100字。');if(new Set(s.keywords.map(k=>k.toLowerCase())).size!==s.keywords.length)throw Error('同一国家的关键词不能重复。');if(s.category_url){let u;try{u=new URL(s.category_url)}catch{throw Error('类目链接需为完整的HTTPS网址。')}if(u.protocol!=='https:'||s.category_url.length>2000||/\s/.test(s.category_url))throw Error('类目链接需为完整的HTTPS网址。');}}return {sites,timezone:'Asia/Shanghai'};}
export function createAPI(client){return {
 async user(){const {data,error}=await client.auth.getUser();if(error||!data?.user)return null;return data.user;},
 async list(page,purpose='normal'){let query=client.from('market_tasks').select('id,name,input,status,created_at,updated_at');if(AUTOMATION_TASK_IDS.length)query=purpose==='automation'?query.in('id',AUTOMATION_TASK_IDS):query.not('id','in','('+AUTOMATION_TASK_IDS.join(',')+')');else if(purpose==='automation')return [];const {data,error}=await query.order('updated_at',{ascending:false}).order('id').range(page*10,page*10+9);if(error)throw error;return data;},
 async task(id){if(!UUID.test(id))throw {message:'MARKET_ACCESS_DENIED'};const {data,error}=await client.from('market_tasks').select('id,name,input,status,revision,report_file_path,created_at,updated_at').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw {message:'MARKET_ACCESS_DENIED'};return data;},
 async create(id,name,input){const {data,error}=await client.rpc('market_create_task',{p_id:id,p_name:name,p_input:input});if(error)throw error;return data;}
};}
