import {mountReport} from './report-view.mjs';
import {mountExports} from './export-view.mjs';
import {mountStatistics} from './statistics-view.mjs';
let statsDispose=()=>{},statsTask=null;
import {mountTags} from './tag-view.mjs';
import {isAutomationTask,AUTOMATION_NOTICE} from './task-purpose.mjs';
import {createAPI,validate,friendly,UUID} from './api.mjs';
import {uploadAPI,fileInfo,parseMessage} from './upload.mjs';
import {mountSamples} from './sample-view.mjs';
import {mountImports} from './import-view.mjs';
const $=s=>document.querySelector(s),app=$('#app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const countries={US:'美国 US',UK:'英国 UK',DE:'德国 DE',FR:'法国 FR',IT:'意大利 IT',ES:'西班牙 ES',CA:'加拿大 CA',JP:'日本 JP',AU:'澳大利亚 AU'};
const labels=['父体列表与标签','产品类型定义','搜索量需求趋势','销量与销售额趋势','品牌占比与销售额','链接销量占比','价格段分布','广告流量占比','评分占比','上架趋势','卖家所属地','BuyBox类型','AI 解读与市场方向建议'];
const status=s=>({draft:'待提交资料',queued:'等待导入',importing:'导入整理中',awaiting_sample:'待确认样本',sample_confirmed:'样本已确认',awaiting_tags:'待确认标签',tags_confirmed:'标签已确认',needs_input:'待补充资料',budget_paused:'额度不足',failed:'处理失败',completed:'已完成'}[s]||'处理中');
let client,api,u,user,page=0,taskPurpose='normal',epoch=0,busy=false,timer,dispose=()=>{},sampleDispose=()=>{},tagDispose=()=>{},siteSequence=0;
const pendingKey=()=> 'market-upload-pending-'+user.id;
const message=(text)=>{const box=$('#page-error');if(box)box.textContent=text;};
const describe=e=>String(e?.message||'').startsWith('MARKET_')?({MARKET_REPLACE_INVALID_SOURCE:'请按错误提示更换文件后再提交。',MARKET_TWO_FILES_REQUIRED:'请为每个国家上传产品信息和历史趋势两份文件。',MARKET_TASK_LOCKED:'任务正在处理，暂时不能更换原件。',MARKET_UPLOAD_MISSING:'文件未上传完整，请重新选择原文件后提交。',MARKET_SOURCE_INVALID:'文件信息不符合要求，请选择.xlsx文件。',MARKET_SOURCE_VERSION_LIMIT:'文件更换次数过多，请创建新任务。'}[e.message]||friendly(e)):e instanceof Error?e.message:friendly(e);
function pending(){try{return JSON.parse(sessionStorage.getItem(pendingKey())||'null')}catch{return null;}}
function savePending(p){sessionStorage.setItem(pendingKey(),JSON.stringify(p));}
function login(){app.innerHTML='<section class="panel logout-note"><h1>请先登录工作台</h1><p class="intro">使用现有工作台账号查看你的市场调研任务。</p><a href="/?next='+encodeURIComponent(location.pathname.includes('/report/')&&UUID.test(new URLSearchParams(location.search).get('task')||'')?'market-research/report/?task='+new URLSearchParams(location.search).get('task'):'market-research/'+(location.hash.startsWith('#task/')?location.hash:''))+'">前往登录 →</a></section>';$('#account').textContent='未登录';$('#logout').hidden=true;}
function addSite(site={country:'US',keywords:[],category_url:''},known=[],locked=false){const n=siteSequence++,el=document.createElement('div');el.className='site';el.innerHTML=`<div class="site-head"><label for="country-${n}">国家</label><select class="country" id="country-${n}" ${locked?'disabled':''}>${Object.entries(countries).map(([k,v])=>`<option value="${k}" ${k===site.country?'selected':''}>${v}</option>`).join('')}</select>${locked?'':'<button class="remove-site" type="button">移除</button>'}</div><div class="field"><label for="keywords-${n}">ABA 品名词 <small>每行一个，最多3个</small></label><textarea class="keywords" id="keywords-${n}" ${locked?'readonly':''}>${esc(site.keywords.join('\n'))}</textarea></div><div class="field"><label for="category-${n}">类目链接 <small>选填</small></label><input class="category" id="category-${n}" type="url" maxlength="2000" value="${esc(site.category_url)}" ${locked?'readonly':''}></div><div class="upload-fields">${[['products','产品信息'],['history','历史趋势']].map(([kind,label])=>{const old=known.find(x=>x.country===site.country&&x.kind===kind);return `<div class="field"><label for="${kind}-${n}">${label}文件</label><input id="${kind}-${n}" data-kind="${kind}" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><small>${old?esc(old.filename)+' · '+(old.status==='uploaded'?'已上传，可保留':'可选择原文件继续上传'):'选择.xlsx文件，最大30 MiB'}</small></div>`}).join('')}</div>`;
el.querySelector('.remove-site')?.addEventListener('click',()=>{el.remove();siteButtons()});$('#sites').append(el);siteButtons();}
function siteButtons(){const sites=[...document.querySelectorAll('.site')];sites.forEach(s=>{const b=s.querySelector('.remove-site');if(b)b.disabled=sites.length===1});if($('#add-site'))$('#add-site').disabled=sites.length>=3;}
function form(root,task=null,known=[]){const p=!task?pending():null,initial=task||p;root.innerHTML=`<h2>${task?'上传资料':'创建任务'}</h2><form id="create-form">${task?'':`<div class="field"><label for="name">任务名称</label><input id="name" maxlength="80" required value="${esc(p?.name||'')}" placeholder="例如：洗衣机顶部台 · 美国市场"></div>`}<div id="sites"></div><div class="actions">${task?'':'<button id="add-site" type="button">＋ 添加国家</button>'}<button class="primary" type="submit">${initial?'继续提交':'创建并导入'}</button>${p?'<button id="new-task" type="button">新建另一任务</button>':''}</div><p id="upload-progress" role="status"></p><p id="page-error" class="error" role="alert"></p></form>`;
const prior=known.length?known:(p?.files||[]);for(const s of initial?.input.sites||[{country:'US',keywords:[],category_url:''}])addSite(s,prior,!!task);
if($('#add-site'))$('#add-site').onclick=()=>{const used=[...document.querySelectorAll('.country')].map(x=>x.value);addSite({country:Object.keys(countries).find(x=>!used.includes(x)),keywords:[],category_url:''})};
if($('#new-task'))$('#new-task').onclick=()=>{sessionStorage.removeItem(pendingKey());render()};$('#create-form').onsubmit=e=>submit(e,task,known);}
async function submit(e,task,known){e.preventDefault();if(busy)return;message('');const name=task?.name||$('#name').value.trim();let input,files=[],p=task?{id:task.id,name:task.name,input:task.input,files:known.map(x=>({country:x.country,kind:x.kind,filename:x.filename,bytes:x.file_bytes,sha256:x.sha256,status:x.status}))}:pending();
try{input=task?.input||validate(name,[...document.querySelectorAll('.site')].map(s=>({country:s.querySelector('.country').value,keywords:s.querySelector('.keywords').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),category_url:s.querySelector('.category').value.trim()})));
if(p&&(p.name!==name||JSON.stringify(p.input)!==JSON.stringify(input)))throw Error('上次提交尚未完成。请保留原任务信息继续，或选择“新建另一任务”。');
busy=true;$('#create-form').querySelectorAll('button,input,select,textarea').forEach(x=>x.disabled=true);
for(const s of document.querySelectorAll('.site')){const country=s.querySelector('.country').value;for(const kind of ['products','history']){const file=s.querySelector(`[data-kind=${kind}]`).files[0];const prior=p?.files?.find(x=>x.country===country&&x.kind===kind);let info;if(file)info=await fileInfo(file);else if(prior)info={filename:prior.filename,bytes:prior.bytes??prior.file_bytes,sha256:prior.sha256};else throw Error(`${countries[country]}：请选择${kind==='products'?'产品信息':'历史趋势'}文件。`);files.push({country,kind,...info,file});}}
p={id:p?.id||crypto.randomUUID(),name,input,files:files.map(({file,...meta})=>meta)};savePending(p);$('#upload-progress').textContent='正在登记任务…';await api.create(p.id,name,input);
for(let i=0;i<files.length;i++){const f=files[i];$('#upload-progress').textContent=`正在上传 ${i+1}/${files.length}：${f.filename}`;await u.upload(p.id,f.country,f.kind,f.file,f);}
$('#upload-progress').textContent='正在提交导入…';await u.submit(p.id);sessionStorage.removeItem(pendingKey());location.hash='task/'+p.id;await render();
}catch(e){message(describe(e));}finally{busy=false;if($('#create-form')){$('#create-form').querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);if(task)document.querySelectorAll('.country').forEach(x=>x.disabled=true);siteButtons();}}}
async function home(stamp){app.innerHTML='<h1>市场调研与开发</h1><p class="intro">上传产品数据，整理产品，再形成市场判断。</p><section class="panel" id="new-form"></section><section class="panel"><div class="row"><h2>我的任务</h2><div class="task-list-actions"><label for="task-purpose">显示</label><select id="task-purpose"><option value="normal">我的任务</option><option value="automation">验收测试任务</option></select><button id="refresh">刷新</button></div></div><div class="table-wrap"><table><thead><tr><th>任务</th><th>国家</th><th>状态</th><th class="date-cell">创建时间</th><th></th></tr></thead><tbody id="tasks"></tbody></table></div><div class="row pager"><button id="prev">上一页</button><span id="page-label"></span><button id="next">下一页</button></div></section>';form($('#new-form'));$('#task-purpose').value=taskPurpose;let listSequence=0;
async function list(){const sequence=++listSequence;try{const rows=await api.list(page,taskPurpose);if(stamp!==epoch||sequence!==listSequence||!$('#tasks'))return;$('#tasks').innerHTML=rows.map(t=>`<tr><td>${esc(t.name)}${isAutomationTask(t)?'<span class="test-task-badge">验收测试</span>':''}</td><td>${esc(t.input.sites.map(s=>s.country).join(' / '))}</td><td><span class="badge">${esc(status(t.status))}</span></td><td class="date-cell">${esc(new Date(t.created_at).toLocaleDateString('zh-CN'))}</td><td><a href="#task/${t.id}">打开</a></td></tr>`).join('')||'<tr><td colspan="5">暂无任务</td></tr>';$('#prev').disabled=page===0;$('#next').disabled=rows.length<10;$('#page-label').textContent=`第 ${page+1} 页`;}catch(e){if(stamp===epoch)message(describe(e));}}
$('#task-purpose').onchange=()=>{taskPurpose=$('#task-purpose').value;page=0;list()};$('#refresh').onclick=list;$('#prev').onclick=()=>{page=Math.max(0,page-1);list()};$('#next').onclick=()=>{page++;list()};await list();}
function tabs(){const items=[...document.querySelectorAll('[role=tab]')];const activate=b=>items.forEach(x=>{const yes=x===b;x.setAttribute('aria-selected',String(yes));x.tabIndex=yes?0:-1;$('#'+x.getAttribute('aria-controls')).hidden=!yes});items.forEach((b,i)=>{b.onclick=()=>activate(b);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;activate(items[n]);items[n].focus()}}});}
async function detail(t,stamp,report){app.innerHTML=`<a href="${report?'/market-research/#task/'+t.id:'#'}">← ${report?'返回任务':'我的任务'}</a><section class="panel"><div class="row"><h1 class="task-name">${esc(t.name)}</h1><span class="badge" id="task-status">${esc(status(t.status))}</span></div>${isAutomationTask(t)?`<p class="test-task-notice" role="note">${esc(AUTOMATION_NOTICE)}</p>`:''}<div class="summary">${t.input.sites.map(s=>`<span>${esc(countries[s.country]||s.country)} · ${esc(s.keywords.join('、'))}</span>`).join('')}</div>${report?'<div id="standalone-report"></div>':`<div class="materials-line"><span id="materials-count">任务资料</span><button id="view-materials" disabled type="button" aria-haspopup="dialog">查看</button></div><div class="tabs" role="tablist"><button role="tab" id="tab-research" aria-selected="true" aria-controls="panel-research">市场调研</button><button role="tab" id="tab-competitor" aria-selected="false" tabindex="-1" aria-controls="panel-competitor">竞品分析</button><button role="tab" id="tab-project" aria-selected="false" tabindex="-1" aria-controls="panel-project">开发立项判断</button></div><section class="tab-panel" role="tabpanel" id="panel-research" aria-labelledby="tab-research"><div class="row"><h2>市场调研</h2><button id="export-download" disabled>下载报告</button></div><div class="compact-grid">${labels.map((x,i)=>`<button disabled><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join('')}</div><div id="sample-content"></div><div id="tag-content"></div><div id="statistics-content"></div></section><section class="tab-panel" role="tabpanel" id="panel-competitor" aria-labelledby="tab-competitor" hidden></section><section class="tab-panel" role="tabpanel" id="panel-project" aria-labelledby="tab-project" hidden></section><dialog id="materials-drawer" aria-labelledby="materials-title"><div class="drawer-head"><h2 id="materials-title">任务资料</h2><button id="close-materials" type="button" aria-label="关闭任务资料">关闭</button></div><div class="drawer-body"><div id="source-files"></div><div id="import-content"></div></div></dialog>`}</section>`;if(report){await mountReport($('#standalone-report'),t,client,()=>stamp===epoch);return;}tabs();mountExports($('#panel-research'),t,client,()=>stamp===epoch);const root=$('#import-content'),drawer=$('#materials-drawer');let loaded=false;const known=await u.sources(t.id);if(stamp!==epoch)return;
$('#materials-count').textContent='任务资料 · '+known.filter(s=>s.status==='uploaded').length+'份文件';
$('#source-files').innerHTML=known.length?'<ul class="source-files">'+known.map((s,i)=>`<li><div><strong>${esc(s.country)} · ${s.kind==='products'?'产品信息':'历史趋势'}</strong><span>${esc(s.filename)}</span></div>${s.status==='uploaded'?`<button type="button" data-source="${i}">下载原件</button>`:'<small>待上传</small>'}</li>`).join('')+'</ul><p id="source-error" class="error" role="alert"></p>':'<p class="muted">尚未上传文件</p>';
for(const button of drawer.querySelectorAll('[data-source]'))button.onclick=async()=>{button.disabled=true;try{const source=known[Number(button.dataset.source)],blob=await u.original(source.raw_path);if(stamp!==epoch)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=source.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{if(stamp===epoch)$('#source-error').textContent='原文件暂时无法下载，请重试。';}finally{button.disabled=false;}};
$('#view-materials').onclick=async()=>{drawer.showModal();document.body.classList.add('materials-open');if(['awaiting_sample','sample_confirmed','awaiting_tags','tags_confirmed'].includes(t.status)&&!loaded){loaded=true;root.innerHTML='<p class="muted">正在读取原始数据…</p>';try{const results=await u.results(t.id,t.revision);if(stamp!==epoch)return;const clean=await mountImports(root,results,u,()=>stamp===epoch)||(()=>{});if(stamp===epoch)dispose=clean;else clean();}catch{loaded=false;if(stamp===epoch)root.innerHTML='<p class="error">资料暂时无法读取，请关闭后重试。</p>';}}};
$('#view-materials').disabled=false;
$('#close-materials').onclick=()=>drawer.close();drawer.addEventListener('close',()=>document.body.classList.remove('materials-open'));drawer.addEventListener('click',e=>{if(e.target===drawer){const r=drawer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)drawer.close();}});

if(['draft','needs_input'].includes(t.status)){const jobs=await u.jobs(t.id);if(stamp!==epoch)return;form(root,t,known);if(t.status==='needs_input'){message(parseMessage(jobs[0]?.error_code));}}
else if(['queued','importing'].includes(t.status)){root.innerHTML='<p class="section-note">'+(t.status==='queued'?'文件已提交，等待导入。':'正在读取工作表、原始字段与图片。')+'</p>';timer=setTimeout(async()=>{try{const next=await api.task(t.id);if(stamp!==epoch)return;const refresh=async()=>{const opened=drawer.open;await render();if(opened)$('#view-materials')?.click();};if(next.status!==t.status)refresh();else timer=setTimeout(refresh,8000);}catch{if(stamp===epoch)root.innerHTML='<p class="error">暂时无法获取进度，请刷新重试。</p>'}},5000);}
else if(['awaiting_sample','sample_confirmed','awaiting_tags','tags_confirmed'].includes(t.status)){root.innerHTML='';}
else root.innerHTML='<p>请核对任务状态后继续。</p>';
if(['awaiting_sample','sample_confirmed','awaiting_tags','tags_confirmed'].includes(t.status)){const clean=await mountSamples($('#sample-content'),t,client,()=>stamp===epoch,next=>{const previous=t.status;if(!['awaiting_tags','tags_confirmed'].includes(previous)){t.status=next;$('#task-status').textContent=status(next);if(previous==='awaiting_sample'&&next==='sample_confirmed')setTimeout(()=>{if(stamp===epoch)render();},0);}else if(next==='awaiting_sample'){t.status=next;setTimeout(()=>{if(stamp===epoch)render();},0);}});if(stamp===epoch)sampleDispose=clean;else clean();}if(['sample_confirmed','awaiting_tags','tags_confirmed'].includes(t.status)&&stamp===epoch){const clean=await mountTags($('#tag-content'),t,client,()=>stamp===epoch,next=>{t.status=next;$('#task-status').textContent=status(next);if(next!=='tags_confirmed'&&statsTask===t.id){statsDispose();statsDispose=()=>{};statsTask=null;$('#statistics-content').innerHTML='';}if(next==='tags_confirmed'&&statsTask!==t.id){statsTask=t.id;mountStatistics($('#statistics-content'),t,client,()=>stamp===epoch).then(clean=>{if(stamp===epoch)statsDispose=clean;else clean();});}});if(stamp===epoch)tagDispose=clean;else clean();}}
async function render(){statsDispose();statsDispose=()=>{};statsTask=null;document.body.classList.remove('materials-open');clearTimeout(timer);dispose();sampleDispose();tagDispose();tagDispose=()=>{};sampleDispose=()=>{};dispose=()=>{};const stamp=++epoch;user=await api.user();if(stamp!==epoch)return;if(!user){login();return;}$('#account').textContent=user.email||'已登录';$('#logout').hidden=false;const report=location.pathname.includes('/report/'),hash=location.hash,id=report?new URLSearchParams(location.search).get('task'):hash.startsWith('#task/')?hash.slice(6):null;
try{if(!report&&!id&&['','#','#home'].includes(hash)){await home(stamp);return;}const t=await api.task(id||'');if(stamp===epoch)await detail(t,stamp,report);}catch(e){if(stamp===epoch)app.innerHTML=`<section class="panel"><p class="error">${esc(describe(e))}</p><a href="/market-research/">返回我的任务</a></section>`;}}
try{const c=window.APP_CONFIG;if(!c?.supabaseUrl||!window.supabase)throw Error('CONFIG');client=window.supabase.createClient(c.supabaseUrl,c.publishableKey,{auth:{storageKey:'keyword-battle-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});api=createAPI(client);u=uploadAPI(client);$('#logout').onclick=async()=>{const {error}=await client.auth.signOut();if(error){message(friendly(error));return;}epoch++;clearTimeout(timer);dispose();sampleDispose();tagDispose();tagDispose=()=>{};sampleDispose=()=>{};document.body.classList.remove('materials-open');login();};client.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT'){epoch++;clearTimeout(timer);dispose();sampleDispose();tagDispose();tagDispose=()=>{};sampleDispose=()=>{};document.body.classList.remove('materials-open');login();}});window.addEventListener('hashchange',()=>{if(!busy)render()});render();}catch{app.innerHTML='<section class="panel"><h1>页面暂时无法连接</h1><p>请检查网络后刷新。</p></section>';}
