import {warningLabel} from './upload.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cell(v,id){if(v===null)return '<span class="muted">—</span>';if(typeof v!=='string')return esc(v);return `<div class="raw-cell ${v.length>18||v.includes('\n')?'raw-cell-wide':''}"><span class="raw-value" id="${id}">${esc(v)}</span><button type="button" class="raw-expand" aria-controls="${id}" aria-expanded="false" hidden>展开</button></div>`;}
export async function mountImports(root,results,u,alive){root.innerHTML='<p class="muted">正在读取原始数据…</p>';const urls=[];let generation=0;
const dispose=()=>{generation++;urls.forEach(x=>URL.revokeObjectURL(x));};
try{const data=await Promise.all(results.map(async r=>({meta:r,data:await u.parsed(r.parsed_path)})));if(!alive())return dispose;
root.innerHTML=`<h2>导入结果</h2><div class="actions"><label for="import-country">国家</label><select id="import-country">${data.map((x,i)=>`<option value="${i}">${esc(x.meta.country)}</option>`).join('')}</select><label for="import-sheet">工作表</label><select id="import-sheet"><option value="products">产品信息</option><option value="sales">历史月销量</option><option value="revenue">历史月销售额</option><option value="price">历史月价格</option></select></div><div id="import-summary"></div><div id="raw-table"></div><div class="row pager"><button id="raw-prev">上一页</button><span id="raw-page"></span><button id="raw-next">下一页</button></div><details><summary>数据检查</summary><div id="import-warnings"></div></details>`;
let page=0;const q=s=>root.querySelector(s);
async function draw(){const stamp=++generation;urls.splice(0).forEach(x=>URL.revokeObjectURL(x));const chosen=data[Number(q('#import-country').value)],parsed=chosen.data,kind=q('#import-sheet').value,table=kind==='products'?parsed.products:parsed.history[kind];const total=table.rows.length,start=page*15,rows=table.rows.slice(start,start+15),summary=parsed.summary;
q('#import-summary').innerHTML=`<p>${esc(table.sheet)} · ${total} 行 · ${table.columns.length} 列 · ${esc(summary.currency)}</p><p class="muted">产品 ${summary.product_rows} 条，图片关联 ${summary.mapped_image_rows} 行；原始列与缺失值均保留。</p>`;
q('#raw-table').innerHTML=`<div class="table-wrap raw-scroll"><table><thead><tr><th>原行号</th>${kind==='products'?'<th>图片</th>':''}${table.columns.map(c=>`<th>${esc(c||'未命名列')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${r.excel_row}</td>${kind==='products'?`<td><div class="raw-image" data-image-row="${r.excel_row}"></div></td>`:''}${r.values.map((v,i)=>`<td>${cell(v,`raw-value-${r.excel_row}-${i}`)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
for(const button of root.querySelectorAll('.raw-expand')){const value=button.previousElementSibling;button.hidden=value.scrollHeight<=value.clientHeight+1;button.onclick=()=>{const expanded=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(expanded));button.textContent=expanded?'收起':'展开';value.classList.toggle('expanded',expanded);};}
q('#raw-page').textContent=`第 ${page+1} / ${Math.max(1,Math.ceil(total/15))} 页`;q('#raw-prev').disabled=page===0;q('#raw-next').disabled=start+15>=total;
q('#import-warnings').innerHTML=parsed.warnings.length?`<ul>${parsed.warnings.map(w=>`<li>${esc(warningLabel[w.code]||w.code)}${w.sheet?' · '+esc(w.sheet):''}${w.count?' · '+esc(w.count)+' 个单元格':''}${w.row?' · 原行 '+w.row:''}${w.column?' · '+esc(w.column):''}${w.asin?' · '+esc(w.asin):''}${w.rows?' · 原行 '+esc(w.rows.join('、')):''}${w.months?' · '+esc(w.months.join('、')):''}${w.asins?' · '+esc(w.asins.join('、')):''}${w.dates?' · '+esc(w.dates.join('、')):''}</li>`).join('')}</ul>`:'<p>未发现解析异常。</p>';
if(kind==='products')for(const r of rows){const images=parsed.images.filter(i=>i.excel_row===r.excel_row&&i.matched);const target=q(`[data-image-row="${r.excel_row}"]`);if(!images.length){target.textContent='—';continue;}for(const img of images){try{const url=await u.image(chosen.meta.image_prefix+img.file);if(stamp!==generation||!alive()){URL.revokeObjectURL(url);return;}urls.push(url);const el=document.createElement('img');el.src=url;el.alt='原行 '+r.excel_row+' 的产品图';el.loading='lazy';target.append(el);}catch{if(stamp===generation&&alive())target.textContent='图片读取失败';}}}}
q('#import-country').onchange=q('#import-sheet').onchange=()=>{page=0;draw()};q('#raw-prev').onclick=()=>{page--;draw()};q('#raw-next').onclick=()=>{page++;draw()};await draw();
}catch{if(alive())root.innerHTML='<p class="error">解析结果暂时无法读取，请刷新重试。</p>';}
return dispose;}
