(() => {
'use strict';const P=window.QAParser,$=id=>document.getElementById(id);
const kinds={product:'产品资料',insight:'消费者洞察',keywords:'关键词',own_reviews:'自家评论',competitor_reviews:'竞品评论'};
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let client,user,task,epoch=0,batches=[],file=null,parsed=null,preview=null,pendingId=null,busy=false,disabledBefore=new Map();
const say=text=>{$('import-message').textContent=text;};
const guard=stamp=>{if(stamp!==epoch||!task)throw Error('任务或登录状态已变化，请重新打开任务。');};
function clear(){epoch++;task=null;batches=[];file=parsed=preview=null;pendingId=null;busy=false;const host=$('imports');if(host)host.replaceChildren();}
function control(tag,id,text){const n=node(tag,text);n.id=id;return n;}
function label(text,input){const l=node('label',text);l.append(input);return l;}
function button(text,fn){const b=node('button',text);b.type='button';b.onclick=fn;return b;}
function rowText(r){return r.cells.map(c=>c.column+': '+c.text).join(' | ');}
function setBusy(value){busy=value;if(value){disabledBefore=new Map();for(const e of $('imports').querySelectorAll('button,input,select,textarea')){disabledBefore.set(e,e.disabled);e.disabled=true;}}else{for(const [e,wasDisabled]of disabledBefore)if(e.isConnected)e.disabled=wasDisabled;disabledBefore.clear();}}
async function action(fn){if(busy)return;const stamp=epoch;setBusy(true);try{await fn(stamp);}catch(e){if(stamp===epoch)say(e.message||'资料操作失败，请重试。');}finally{if(stamp===epoch)setBusy(false);}}
async function open(current,c,u){clear();if(!current||current.unsaved)return;client=c;user=u;task=current;const host=$('imports');
 host.append(node('h2','资料导入'),node('p','先选择分类，再预览字段和来源，确认后保存。原始文件和历次版本都会保留。'));
 const area=node('div');area.className='grid';const kind=control('select','import-kind');for(const [v,t]of Object.entries(kinds)){const o=node('option',t);o.value=v;kind.append(o);}area.append(label('资料分类',kind));
 const replacement=control('select','import-replacement');replacement.append(new Option('作为新资料导入',''));area.append(label('保存方式',replacement));host.append(area);
 const tabs=node('div');tabs.className='grid';const upload=control('input','import-file');upload.type='file';upload.accept='.docx';tabs.append(label('选择文件（单文件不超过10 MB）',upload));const paste=control('textarea','import-paste');paste.rows=5;paste.placeholder='或粘贴文字，每行保留为一个来源段落；最多100000字符';tabs.append(label('文本粘贴（与文件二选一）',paste));host.append(tabs);
 const ownArea=node('div');ownArea.className='grid';const relation=control('select','import-relation');for(const [v,t]of [['own','自家产品'],['competitor','竞品'],['mixed','多产品汇总'],['unconfirmed','归属待确认']])relation.append(new Option(t,v));const product=control('input','import-product');product.value=task.asin||'';product.placeholder='ASIN或产品名称；多产品请逐个列明';ownArea.append(label('资料产品范围',relation),label('文件级产品标识（有来源列时优先使用该列）',product));host.append(ownArea);
 const confirm=control('input','import-own-confirm');confirm.type='checkbox';const confirmLabel=label('我确认无产品标识的内容属于本任务产品',confirm);confirmLabel.className='check-label';host.append(confirmLabel);
 const analyze=button('解析并预览',()=>action(parseSelected));analyze.id='import-parse';host.append(analyze);const message=control('p','import-message');message.setAttribute('role','status');host.append(message,control('div','import-mappings'),control('div','import-preview'),control('div','source-list'));
 const writing=node('section');writing.className='writing';writing.append(node('h3','写作指令（单独保存）'),node('p','这里只保存你明确填写的写作要求，不会执行资料文件里的指令。'));const instructions=control('textarea','writing-content');instructions.rows=5;writing.append(instructions,button('保存写作指令新版本',()=>action(saveWriting)),control('p','writing-state'));host.append(writing);
 function changeKind(){parsed=preview=null;$('import-mappings').replaceChildren();$('import-preview').replaceChildren();kind.value==='product'?upload.accept='.docx':upload.accept='.xlsx,.csv';if(kind.value==='own_reviews'){relation.value='own';product.value='';}else if(kind.value==='competitor_reviews'){relation.value='competitor';product.value='';}else if(kind.value==='insight'){relation.value='mixed';product.value='';}else{relation.value='own';product.value=task.asin||'';}confirm.checked=false;renderReplacements();}
 kind.onchange=changeKind;replacement.onchange=()=>{preview=null;$('import-preview').replaceChildren();};
 try{await action(async stamp=>{await loadBatches(stamp);const res=await client.from('qa_writing_versions').select('content,created_at').eq('task_id',task.id).order('created_at',{ascending:false}).limit(1);guard(stamp);if(res.error)throw Error('写作指令读取失败，请检查阶段2配置。');if(res.data[0]){instructions.value=res.data[0].content;$('writing-state').textContent='已恢复最新版本 · '+new Date(res.data[0].created_at).toLocaleString('zh-CN');}});}catch{}
}
async function loadBatches(stamp){let all=[],start=0;while(true){const res=await client.from('qa_sources').select('id,kind,filename,raw_path,raw_sha256,interpretation_sha256,file_bytes,pasted,mappings,ownership,notes,stats,replaces_id,series_id,version,created_at').eq('task_id',task.id).order('created_at',{ascending:true}).order('id',{ascending:true}).range(start,start+499);guard(stamp);if(res.error)throw Error('资料列表读取失败，请检查阶段2私有表配置或重试。');all.push(...res.data);if(res.data.length<500)break;start+=500;}batches=all;renderReplacements();renderSources();}
function latest(){const old=new Set(batches.map(b=>b.replaces_id).filter(Boolean));return batches.filter(b=>!old.has(b.id));}
function renderReplacements(){const sel=$('import-replacement');if(!sel)return;const previous=sel.value;sel.replaceChildren(new Option('作为新资料导入',''));for(const b of latest().filter(b=>b.kind===$('import-kind').value))sel.append(new Option(b.filename+' · 替换版本'+b.version,b.id));sel.value=[...sel.options].some(o=>o.value===previous)?previous:'';}
async function parseSelected(stamp){const selected=$('import-file').files[0],text=$('import-paste').value;if(selected&&text.trim())throw Error('请只选择文件或粘贴文本中的一种，避免混合来源。');if(!selected&&!text.trim())throw Error('请选择文件或粘贴非空文字。');const kind=$('import-kind').value;file=selected||new File([text],'粘贴-'+kinds[kind]+'.txt',{type:'text/plain'});say('正在本地解析，不调用模型…');parsed=await P.parse(file,kind,!selected);guard(stamp);preview=null;pendingId=null;renderMappings();say(file.name+'：已解析，请核对各工作表的字段和样例，再点击“检查对应关系”。');}
function renderMappings(){const host=$('import-mappings');host.replaceChildren();host.append(node('h3','字段与样例'));parsed.groups.forEach((g,index)=>{const box=node('fieldset');box.dataset.group=String(index);box.append(node('legend',g.name));const proposal=P.propose(g,parsed.kind);const mode=node('select');mode.dataset.role='mode';mode.append(new Option('逐行保留全部文字','all'),new Option('按表头对应字段','columns'));mode.value=proposal.allCells?'all':'columns';if(g.mode==='table'&&['keywords','own_reviews','competitor_reviews'].includes(parsed.kind))mode.value='columns';box.append(label('读取方式',mode));
 const header=node('input');header.type='number';header.min='0';header.value=proposal.headerRow;header.dataset.role='header';box.append(label('表头所在行号（0表示没有表头）',header));
 const columns=[...new Set(g.rows.flatMap(r=>r.cells.map(c=>c.column)))];const controls=node('div');controls.className='grid';for(const [key,title]of [['text','内容 / 关键词'],['title','评论标题'],['body','评论正文'],['product','来源 ASIN / 产品标识'],['sourceId','原始序号（不是系统编号）']]){const select=node('select');select.dataset.field=key;select.append(new Option('未指定',''));for(const col of columns){const h=g.rows.find(r=>r.row===Number(header.value))?.cells.find(c=>c.column===col)?.text||'';select.append(new Option(col+(h?' · '+h:''),col));}select.value=proposal.fields[key]||'';controls.append(label(title,select));}box.append(controls);
 const example=node('pre',g.rows.slice(0,3).map(r=>'第'+r.row+'行/段：'+rowText(r)).join('\n'));example.className='source-text';box.append(node('p','以下只展示前3条样例；检查后可逐条翻页查看全部记录。'),example);host.append(box);});host.append(button('检查对应关系',()=>action(buildPreview)));}
function readMappings(){const maps={};for(const box of $('import-mappings').querySelectorAll('fieldset')){const g=parsed.groups[Number(box.dataset.group)],allCells=box.querySelector('[data-role="mode"]').value==='all';if(g.mode==='table'&&['keywords','own_reviews','competitor_reviews'].includes(parsed.kind)&&allCells)throw Error(g.name+'：此分类需要指定关键词或评论内容列，不能整行混合导入。');maps[g.name]={headerRow:Number(box.querySelector('[data-role="header"]').value),allCells,fields:Object.fromEntries([...box.querySelectorAll('[data-field]')].map(s=>[s.dataset.field,s.value]))};}return maps;}
function readOwnership(){return {relation:$('import-relation').value,product:$('import-product').value,confirmOwn:$('import-own-confirm').checked};}
async function buildPreview(stamp){if(!parsed)throw Error('请先解析文件。');const mappings=readMappings(),ownership=readOwnership(),existing=[];for(const b of latest()){const res=await client.from('qa_sources').select('records').eq('id',b.id).single();guard(stamp);if(res.error)throw Error('已有来源读取失败，未继续去重。');existing.push(res.data);}
 const normalized=await P.normalize(parsed,mappings,ownership,task,existing);guard(stamp);const interpretation=await P.sha(new TextEncoder().encode(JSON.stringify({kind:parsed.kind,mappings,ownership})));guard(stamp);preview={...normalized,mappings,ownership,interpretation,replaces_id:$('import-replacement').value||null};pendingId=null;const match=batches.find(b=>b.kind===parsed.kind&&b.raw_sha256===parsed.digest&&b.interpretation_sha256===interpretation);if(match){say('重复导入：与已保存的“'+match.filename+'”版本'+match.version+'完全一致，原来源仍保留，本次不重复保存。');preview.duplicate=match.id;}else say('检查完成。待确认或错误记录也会连同原文保存，供你修正后另存新版本；不会进入分析。');renderPreview();}
function summary(stats){return '共'+stats.total+'条 · 通过'+stats.success+' · 错误'+stats.failed+' · 待确认'+stats.pending+' · 重复关联'+stats.duplicates+'（记录全部保留） · 空白行'+stats.blank+' · 表头'+stats.headers;}
function renderRecords(host,records){let index=0;const area=node('div'),nav=node('div'),previous=button('上一条',()=>{index--;draw();}),next=button('下一条',()=>{index++;draw();}),position=node('span');nav.className='record-nav';nav.append(previous,position,next);host.append(nav,area);function draw(){const r=records[index];area.replaceChildren();position.textContent=(index+1)+' / '+records.length;previous.disabled=index===0;next.disabled=index===records.length-1;area.append(node('p','编号：'+r.id),node('p',r.source.file+' / '+r.source.sheet+' / '+(r.source.position==='paragraph'?'段落':'行')+r.source.row+(r.source.end_row!==r.source.row?'–'+r.source.end_row:'')),node('p','产品：'+(r.product_ref||'待确认')+' · 归属：'+({own:'自家',competitor:'竞品',mixed:'多产品',unconfirmed:'待确认'}[r.relation]||r.relation)+' · '+({success:'通过',failed:'错误',pending:'待确认'}[r.state])),node('p',r.reasons.join('；')));if(r.duplicate_of)area.append(node('p','重复内容关联记录：'+r.duplicate_of+'；本条原始来源保留。'));const raw=node('pre',JSON.stringify(r.raw,null,2)),clean=node('pre',JSON.stringify(r.normalized,null,2));raw.className=clean.className='source-text';area.append(node('h4','原始内容'),raw,node('h4','整理后的内容'),clean);}draw();}
function renderPreview(){const host=$('import-preview');host.replaceChildren();host.append(node('h3','导入检查结果'),node('p',summary(preview.counts)));for(const note of parsed.notes)host.append(node('p',note));renderRecords(host,preview.records);if(!preview.duplicate){const save=button('确认保存资料',()=>action(saveSource));save.id='import-save';save.className='primary';host.append(save);}else host.append(node('p','相同资料和对应关系已保存，无需重复提交。'));}
async function saveSource(stamp){if(!preview||preview.duplicate)throw Error('请先完成对应关系检查。');if(JSON.stringify(readMappings())!==JSON.stringify(preview.mappings)||JSON.stringify(readOwnership())!==JSON.stringify(preview.ownership)||($('import-replacement').value||null)!==preview.replaces_id)throw Error('对应关系、归属或保存方式已变化，请重新检查。');
 const id=pendingId||(pendingId=crypto.randomUUID()),ext=parsed.pasted?'txt':file.name.split('.').pop().toLowerCase(),rawPath='QA/'+user.id+'/'+task.id+'/'+id+'/source.'+ext;const exists=await client.from('qa_sources').select('id').eq('id',id).maybeSingle();guard(stamp);if(exists.error)throw Error('保存前核对失败，请重试。');
 if(!exists.data){const upload=await client.storage.from('keyword-battle-inbox').upload(rawPath,file,{upsert:false,contentType:parsed.pasted?'text/plain':file.type||'application/octet-stream'});guard(stamp);if(upload.error){const prior=await client.storage.from('keyword-battle-inbox').download(rawPath);guard(stamp);if(prior.error||await P.sha(await prior.data.arrayBuffer())!==parsed.digest)throw Error('原文件上传失败；尚未登记导入成功，请重试。');}
  const result=await client.from('qa_sources').insert({id,task_id:task.id,kind:parsed.kind,filename:file.name,raw_path:rawPath,raw_sha256:parsed.digest,interpretation_sha256:preview.interpretation,file_bytes:file.size,pasted:parsed.pasted,mappings:preview.mappings,ownership:preview.ownership,records:preview.records,notes:parsed.notes,stats:preview.counts,replaces_id:preview.replaces_id});guard(stamp);if(result.error){if(result.error.code==='23505')throw Error('资料已存在或旧版本已被替换，请刷新来源列表后核对。原文件保留，未覆盖。');throw Error('原文件已上传，但来源登记失败；点击保存可重试同一导入，不要重新上传。');}}
 await loadBatches(stamp);say('资料已保存，刷新后可恢复。'+summary(preview.counts));$('import-save')?.remove();window.dispatchEvent(new Event('qa-sources-changed'));
}
function renderSources(){const host=$('source-list');host.replaceChildren();host.append(node('h3','已保存来源与版本'));if(!batches.length){host.append(node('p','尚未导入资料。产品资料是后续生成的必填项，其他分类可选。'));return;}if(!latest().some(b=>b.kind==='product'&&b.stats.success>0))host.append(node('p','待补：尚无通过基础检查的产品资料。'));const superseded=new Set(batches.map(b=>b.replaces_id).filter(Boolean));for(const b of batches){const box=node('article');box.className='source-item';box.append(node('h4',kinds[b.kind]+' · '+b.filename+' · 版本'+b.version+(superseded.has(b.id)?'（历史）':'（当前）')),node('p',summary(b.stats)));const actions=node('div');actions.className='record-nav';actions.append(button('逐条对照原文',()=>action(async stamp=>{const res=await client.from('qa_sources').select('records').eq('id',b.id).single();guard(stamp);if(res.error)throw Error('来源记录读取失败。');const detail=node('div');detail.className='source-detail';box.querySelector('.source-detail')?.remove();renderRecords(detail,res.data.records);box.append(detail);})),button('下载原始文件',()=>action(async stamp=>{const res=await client.storage.from('keyword-battle-inbox').download(b.raw_path);guard(stamp);if(res.error)throw Error('原始文件读取失败或当前账号无权访问。');const url=URL.createObjectURL(res.data),a=node('a');a.href=url;a.download=b.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})));box.append(actions);host.append(box);}}
async function saveWriting(stamp){const content=$('writing-content').value;if(!content.trim())throw Error('写作指令为空，未保存。');if(Array.from(content).length>P.LIMIT.chars)throw Error('写作指令超过100000字符，未保存。');const res=await client.from('qa_writing_versions').insert({id:crypto.randomUUID(),task_id:task.id,content});guard(stamp);if(res.error)throw Error('写作指令保存失败，请重试。');$('writing-state').textContent='已保存为独立新版本，资料内容未改变。';}
window.QAImports={open,clear};
})();
