(function(){
'use strict';
function equal(a,b){if(a===b)return true;if(!a||!b||typeof a!=='object'||typeof b!=='object')return false;if(Array.isArray(a)||Array.isArray(b))return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>equal(v,b[i]));const k=Object.keys(a);return k.length===Object.keys(b).length&&k.every(x=>Object.prototype.hasOwnProperty.call(b,x)&&equal(a[x],b[x]));}
function create(client,user,task){let expected=0,pending=null;const bucket=client.storage.from('keyword-battle-inbox');
async function finish(row){if(!row.pending_id)return row;const prefix='QA/'+user.id+'/'+task.id+'/stage4/'+row.pending_id+'/';for(const [name,data]of [['question_plan.json',row.pending_plan],['question_selection.json',row.pending_selection]]){const upload=await bucket.upload(prefix+name,new Blob([JSON.stringify(data)],{type:'application/json'}),{upsert:false,contentType:'application/json'});if(upload.error){const old=await bucket.download(prefix+name);if(old.error||!equal(JSON.parse(await old.data.text()),data))throw Error('新清单文件尚未保存完整，可重试；旧清单仍保留。');}}const done=await client.rpc('qa_complete_question_plan',{p_task:task.id,p_operation:row.pending_id});if(done.error)throw Error('文件已上传，清单切换尚未完成，请重试。');return done.data;}
async function load(){const r=await client.from('qa_question_current').select('*').eq('task_id',task.id).maybeSingle();if(r.error)throw Error('问题清单保存配置尚未就绪');if(!r.data){expected=0;return null;}let row=r.data;if(row.pending_id)row=await finish(row);expected=row.revision;return row.state;}
async function save(state){if(state.simulation||state.task_id!==task.id)throw Error('模拟清单不能写入真实任务');const signature=JSON.stringify(state);if(pending&&pending.signature!==signature)throw Error('请先完成上一次保存重试');if(!pending)pending={id:crypto.randomUUID(),signature};const r=await client.rpc('qa_save_question_plan',{p_task:task.id,p_operation:pending.id,p_expected:expected,p_review:state.fact_version,p_context_key:state.context_key,p_questions:state.questions,p_confirm:!!state.confirmation});if(r.error)throw Error(r.error.message==='QA_QUESTION_VERSION_CHANGED'?'其他窗口已保存新清单，请重新打开任务。':'清单保存未完成：'+r.error.message);const row=await finish(r.data);expected=row.revision;pending=null;return row.state;}
async function download(name){if(!['question_plan.json','question_selection.json'].includes(name))throw Error('文件名无效');const r=await client.from('qa_question_current').select('*').eq('task_id',task.id).single();if(r.error||!r.data.operation_id)throw Error('清单尚未保存');const row=r.data,data=name==='question_plan.json'?row.question_plan:row.question_selection;const got=await bucket.download('QA/'+user.id+'/'+task.id+'/stage4/'+row.operation_id+'/'+name);if(got.error||!equal(JSON.parse(await got.data.text()),data))throw Error('文件与当前清单不一致，请停止使用');return got.data;}
return {load,save,download};}
window.QAQuestionStore={create};
})();
