(function(){
'use strict';const C=window.QAReviewCore;
function create(client,user,task){let expected=0,pending=null;const bucket=client.storage.from('keyword-battle-inbox');
 async function sources(){let batches=[],start=0;while(true){const r=await client.from('qa_sources').select('id,version,replaces_id,kind,records,created_at').eq('task_id',task.id).eq('kind','product').order('created_at',{ascending:true}).order('id',{ascending:true}).range(start,start+99);if(r.error)throw Error('产品资料读取失败');batches.push(...r.data);if(r.data.length<100)break;start+=100;}const replaced=new Set(batches.map(b=>b.replaces_id).filter(Boolean));const byId=new Map();for(const b of batches)for(const r of b.records){if(r.relation!=='own')continue;const src={id:r.id,import_id:b.id,version:b.version,current:!replaced.has(b.id),kind:'product',relation:r.relation,product:r.product_ref,file:r.source.file,sheet:r.source.sheet,position:(r.source.position==='paragraph'?'段落':'行')+r.source.row,original:r.raw.text||r.normalized.text};if(!byId.has(src.id)||src.current)byId.set(src.id,src);}return [...byId.values()];}
 async function files(row){const prefix='QA/'+user.id+'/'+task.id+'/stage3/'+row.id+'/';for(const [name,data]of Object.entries({'facts.json':row.facts_json,'fact_conflicts.json':row.conflicts_json,'writing_rules.json':row.rules_json})){const text=JSON.stringify(data);const result=await bucket.upload(prefix+name,new Blob([text],{type:'application/json'}),{upsert:false,contentType:'application/json'});if(result.error){const got=await bucket.download(prefix+name);if(got.error||JSON.stringify(JSON.parse(await got.data.text()))!==text)throw Error('版本文件未保存完整，可重试；已存原文不覆盖。');}}const done=await client.rpc('qa_complete_review',{p_id:row.id});if(done.error)throw Error('版本文件已上传，但保存确认未完成，请重试。');return done.data;}
 async function load(){const r=await client.from('qa_review_versions').select('*').eq('task_id',task.id).order('version',{ascending:false}).limit(1);if(r.error)throw Error('事实确认的保存配置尚未就绪，请先完成阶段3配置。');if(!r.data.length){expected=0;return null;}let row=r.data[0];expected=row.version;if(!row.files_ready)row=await files(row);return row.state;}
 async function save(state){if(state.simulation||state.task_id!==task.id)throw Error('不允许将模拟数据保存为真实任务');const signature=JSON.stringify(state);if(pending&&pending.signature!==signature)throw Error('上一版尚未完成保存，请先重试原操作或重新打开任务。');if(!pending)pending={id:crypto.randomUUID(),signature};const r=await client.rpc('qa_save_review',{p_task:task.id,p_id:pending.id,p_expected:expected,p_state:state});if(r.error)throw Error(r.error.message==='QA_REVIEW_VERSION_CHANGED'?'其他窗口已保存新版，请重新打开任务后修改。':'保存未完成：'+r.error.message);const row=await files(r.data);expected=row.version;pending=null;return row.state;}
 async function versions(){const r=await client.from('qa_review_versions').select('id,version,created_at,files_ready').eq('task_id',task.id).order('version',{ascending:false});if(r.error)throw Error('历史版本读取失败');return r.data;}
 async function download(rowId,name){if(!['facts.json','fact_conflicts.json','writing_rules.json'].includes(name))throw Error('文件名不允许');const q=await client.from('qa_review_versions').select('*').eq('id',rowId).eq('task_id',task.id).single();if(q.error||!q.data.files_ready)throw Error('版本不存在或尚未保存完整');const data=q.data[{ 'facts.json':'facts_json','fact_conflicts.json':'conflicts_json','writing_rules.json':'rules_json'}[name]];const r=await bucket.download('QA/'+user.id+'/'+task.id+'/stage3/'+rowId+'/'+name);if(r.error||JSON.stringify(JSON.parse(await r.data.text()))!==JSON.stringify(data))throw Error('文件与保存版本不一致，请停止使用并联系管理员');return r.data;}
 async function extract(variant){const r=await client.rpc('qa_enqueue_fact_job',{p_task:task.id,p_id:crypto.randomUUID(),p_variant:variant,p_accept_cost:true});if(r.error)throw Error(r.error.message);return r.data;}
 async function factJob(){const r=await client.from('qa_fact_jobs').select('*').eq('task_id',task.id).maybeSingle();if(r.error)throw Error('事实整理配置尚未就绪');return r.data;}
 return {load,save,sources,versions,download,extract,factJob};}
window.QAReviewStore={create};
})();
