(function(){
'use strict';const C=window.QAReviewCore,n=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};let epoch=0,ctx=null;
function btn(text,fn){const b=n('button',text);b.type='button';b.onclick=()=>act(fn);return b;}
function input(parent,title,value,multi=false){const l=n('label',title),e=n(multi?'textarea':'input');e.value=value??'';l.append(e);parent.append(l);return e;}
function details(parent,label){const d=n('details');d.append(n('summary',label));parent.append(d);return d;}
function say(c,text){if(ctx===c)c.message.textContent=text;}
async function act(fn){const c=ctx;if(!c||c.busy)return;c.busy=true;try{await fn(c);}catch(e){say(c,e.message);}finally{c.busy=false;}}
async function save(c,next){const returned=await c.store.save(next);if(ctx!==c)return;c.state=returned;c.selected.clear();draw(c);say(c,'已保存，刷新后可以继续。');window.dispatchEvent(new Event('qa-review-changed'));}
function draw(c){const h=c.host,s=c.state;h.replaceChildren();h.className='imports';h.append(n('h2','确认事实和写作规则'),n('p','核对原文后勾选事实；不确定的暂不采用。不会在本页生成问答。'));c.message=n('p');c.message.setAttribute('role','status');h.append(c.message);
 if(!s.facts.length){const entry=details(h,'从本任务产品资料整理事实');entry.open=true;const variant=input(entry,'本次型号/变体',s.variant==='未指定'?'':s.variant);entry.append(n('p','仅使用本任务自家产品参数；候选事实不会自动确认。没有额外指令时沿用美国站、英文附中文等固定设置。'),btn('整理候选事实',async()=>{if(!variant.value.trim()||variant.value==='未指定')throw Error('请明确型号/变体');if(!confirm('从本任务自家产品资料整理候选事实，豆包Seed 2.0 Lite最多1次调用、上限0.05元；失败停止、不自动重试。是否授权？'))return;await c.store.extract(variant.value.trim());say(c,'请求已提交，请稍后点击读取整理结果；刷新不会重复调用。');}),btn('读取事实整理结果',async()=>{const j=await c.store.factJob();if(!j)throw Error('尚未发起事实整理');if(j.status==='failed')throw Error(j.failure_reason);if(j.status!=='succeeded')throw Error('正在整理，请稍后读取；不要重复提交');const current=await c.store.sources(),candidate=structuredClone(j.result);if(candidate.task_id!==c.task.id||candidate.product!==(c.task.asin||c.task.id))throw Error('结果产品不匹配');for(const src of candidate.sources){const live=current.find(x=>x.id===src.id&&x.current);if(!live||['id','import_id','version','product','original','current'].some(k=>live[k]!==src[k]))throw Error('原资料已变化，请停止采用旧结果');}candidate.sources=current;candidate.facts_confirmation=candidate.rules_confirmation=null;await save(c,candidate);}));}
 const imp=details(h,s.facts.length?'导入新的整理结果':'导入已整理的事实');imp.append(n('p','选择本项目交付的state.json。只接受能对应到本任务自家资料的候选事实；不会自动确认。'));const file=n('input');file.type='file';file.accept='.json';imp.append(file,btn('读取整理结果',async()=>{if(!file.files[0])throw Error('请选择整理结果文件');const candidate=JSON.parse(await file.files[0].text());if(candidate.simulation||candidate.product!==(c.task.asin||c.task.id)||!Array.isArray(candidate.facts))throw Error('这不是本产品的真实候选结果');if(s.facts.length)throw Error('本任务已有事实；请逐项修改，避免覆盖确认记录。');const sources=await c.store.sources();const imported=structuredClone(candidate);imported.task_id=c.task.id;imported.product=c.task.asin||c.task.id;imported.sources=sources;imported.facts_confirmation=imported.rules_confirmation=null;for(const f of imported.facts){const source=sources.find(x=>x.id===f.source_id&&x.current);if(f.provided_by!=='用户提供'){if(!source||source.product!==f.product||!source.original.includes(f.quote))throw Error('候选事实无法对应本任务当前原文：'+f.attribute);f.source_version=source.version;}f.status=f.status==='暂不采用'?'暂不采用':'待确认';f.confirmed_at=null;f.original_reviewed=false;}for(const r of imported.rules){r.status=r.status==='暂不采用'?'暂不采用':'待确认';r.confirmed_at=null;}await save(c,imported);}));
 const summary=n('p','目标产品：'+s.product+' / '+s.variant+' · 保存版本 '+s.revision);h.append(summary);const problemMap=new Map(C.problems(s).facts.map(x=>[x.id,x.problems]));
 for(const f of s.facts){const box=n('article');box.className='source-item';const l=n('label'),check=n('input');check.type='checkbox';l.className='check-label';check.checked=c.selected.has(f.id);const blockers=(problemMap.get(f.id)||[]).filter(x=>x!=='尚未逐项核对数值、单位和原文限定');check.disabled=f.status==='有冲突'||f.status==='暂不采用'||blockers.length>0;check.onchange=()=>check.checked?c.selected.add(f.id):c.selected.delete(f.id);l.append(check,document.createTextNode(f.attribute+'：'+f.value+' · '+f.status));box.append(l,n('p','单位：'+f.unit+'；适用条件：'+f.conditions));if(blockers.length)box.append(n('p','待补：'+blockers.join('；')));const src=details(box,'看原文');src.append(n('pre',f.user_original||f.quote));src.lastChild.className='source-text';const source=s.sources.find(x=>x.id===f.source_id);src.append(n('p',source?[source.file,source.sheet,source.position].join(' / '):'用户提供；非第三方验证'));
 const edit=details(box,'修改或暂不采用');const fields={};for(const [k,t]of [['variant','产品规格/变体'],['value','内容'],['unit','单位'],['conditions','条件及限制']])fields[k]=input(edit,t,f[k],k==='conditions');const reason=input(edit,'原因','');edit.append(btn('保存修改',()=>save(c,C.editFact(s,f.id,Object.fromEntries(Object.entries(fields).map(([k,e])=>[k,e.value])),reason.value))),btn('暂不采用',()=>save(c,C.excludeFact(s,f.id,reason.value))));const history=details(box,'修改记录');history.append(n('p','事实编号 '+f.id+' · 版本 '+f.version));for(const x of f.history)history.append(n('p',x.at+' · '+x.reason));h.append(box);}
 h.append(btn('确认勾选事实（我已核对原文）',()=>{if(!c.selected.size)throw Error('请先勾选要确认的事实');let next=s;for(const id of c.selected)next=C.editFact(next,id,{original_reviewed:true},'用户明确勾选并确认已核对原文');return save(c,C.confirmSelected(next,[...c.selected]));}));
 const ruleBox=details(h,'写作规则（沿用已确认口径，可逐条查看）');ruleBox.open=!s.facts.length;for(const r of s.rules){const box=n('div');box.append(n('p',r.original),n('p','理解：'+r.understanding),n('p','检查：'+r.check));const p=C.ruleProblems(s,r);if(p.length)box.append(n('p','待确认：'+p.join('；')));box.append(n('p','状态：'+r.status));ruleBox.append(box);}ruleBox.append(btn('确认上述无矛盾写作规则',()=>{let next=s;for(const r of s.rules.filter(r=>r.status!=='暂不采用'))next=C.decideRule(next,r.id,true,'用户确认沿用当前可见写作口径');return save(c,C.confirmSection(next,'rules'));}));
 const advanced=details(h,'补充或修改设置');advanced.append(n('p','修改后需要重新确认；资料正文中的指令不执行。'));const original=input(advanced,'独立写作指令',s.custom_original,true);advanced.append(btn('保存指令原文（重新待确认）',()=>save(c,C.setCustom(s,original.value))));const manual=details(advanced,'补充用户提供事实');const fields={};for(const [key,label,val]of [['attribute','属性',''],['value','值',''],['unit','单位','不适用'],['conditions','条件与限制',''],['user_original','用户提供原文','']])fields[key]=input(manual,label,val,true);manual.append(btn('保存补充事实',()=>save(c,C.addFact(s,{product:s.product,variant:s.variant,provided_by:'用户提供',...Object.fromEntries(Object.entries(fields).map(([k,e])=>[k,e.value]))}))));const fixed=details(advanced,'固定设置');const settingFields={};for(const k of ['quantity','question_max','answer_min','answer_max','length_policy','tone','audience','scenes','must_topics','forbidden','keywords'])settingFields[k]=input(fixed,({quantity:'目标组数',question_max:'问题建议最多英文词数',answer_min:'答案建议最少英文词数',answer_max:'答案建议最多英文词数',length_policy:'长度口径',tone:'语气',audience:'人群',scenes:'场景',must_topics:'必讲主题',forbidden:'禁用表达',keywords:'关键词偏好'})[k],s.settings[k]);fixed.append(btn('保存设置',()=>save(c,C.setSettings(s,Object.fromEntries(Object.entries(settingFields).map(([k,e])=>[k,['quantity','question_max','answer_min','answer_max'].includes(k)?Number(e.value):e.value]))))));for(const r of s.rules){const edit=details(advanced,'调整规则：'+r.original);const u=input(edit,'系统理解',r.understanding,true),ch=input(edit,'检查方式',r.check,true),pending=input(edit,'待确认事项（每行一项）',r.pending.join('\n'),true),why=input(edit,'修改或暂不采用理由','');edit.append(btn('保存规则修订',()=>save(c,C.editRule(s,r.id,{understanding:u.value,check:ch.value,pending:pending.value.split('\n').filter(x=>x.trim())},why.value))),btn('暂不采用这条规则',()=>save(c,C.decideRule(s,r.id,false,why.value))));}
 const gaps=details(h,'待补与不采用的内容');for(const q of s.issues){gaps.append(n('p',q.message+' · '+q.status));const reason=input(gaps,'处理说明','');gaps.append(btn('标记已处理',()=>save(c,C.resolveGap(s,q.id,'已解决',reason.value))));if(!q.critical)gaps.append(btn('接受非关键待补',()=>save(c,C.resolveGap(s,q.id,'接受非关键待补',reason.value))));}h.append(btn('保存本版事实确认',()=>save(c,C.confirmSection(s,'facts'))));const g=C.gate(s);h.append(n('p',g.ready?'事实和规则已确认。阶段3验收完成后，等待阶段4指示。':'尚待确认：'+g.reasons.join('；')));for(const w of g.warnings)h.append(n('p',w));const versions=details(h,'历史版本与JSON文件');versions.append(btn('查看历史版本',async()=>{const list=await c.store.versions();if(ctx!==c)return;for(const v of list){const row=n('div');row.append(n('p','版本'+v.version+' · '+v.created_at+(v.files_ready?'':' · 文件待完成')));for(const name of ['facts.json','fact_conflicts.json','writing_rules.json'])row.append(btn(name,async()=>{const blob=await c.store.download(v.id,name);if(ctx!==c)return;const url=URL.createObjectURL(blob),a=n('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));versions.append(row);}}));}
async function open(task,client,user){clear();if(!task||task.unsaved)return;const stamp=epoch,host=document.getElementById('review');if(!host)return;const c={task,host,store:window.QAReviewStore.create(client,user,task),selected:new Set(),busy:false};ctx=c;c.message=n('p','正在读取事实与规则…');host.append(c.message);try{let s=await c.store.load();if(stamp!==epoch)return;if(!s)s=C.blank(task,false);if(s.product!==(task.asin||task.id))s=C.setTarget(s,task.asin||task.id,'通用');if(s.settings.quantity!==task.qa_count)s=C.setSettings(s,{quantity:task.qa_count});const current=await c.store.sources();if(stamp!==epoch)return;c.state=C.replaceSources(s,current);draw(c);}catch(e){say(c,e.message);}}
function clear(){epoch++;if(ctx)ctx.host.replaceChildren();ctx=null;}
window.QAReview={open,clear};
})();

