(function(root){
'use strict';
const copy=x=>JSON.parse(JSON.stringify(x)),id=()=>globalThis.crypto.randomUUID(),now=()=>new Date().toISOString();
const states=['待确认','已确认','有冲突','暂不采用'];
function requireThat(ok,message){if(!ok)throw Error(message);}
function text(x){return typeof x==='string'&&x.trim().length>0;}
function same(a,b){
 if(a===b)return true;
 if(a===null||b===null||typeof a!=='object'||typeof b!=='object')return false;
 if(Array.isArray(a)||Array.isArray(b))return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>same(v,b[i]));
 const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(k=>Object.prototype.hasOwnProperty.call(b,k)&&same(a[k],b[k]));
}
function blank(task,simulation=false){return {schema_version:1,task_id:task.id,product:task.asin||task.id,variant:'未指定',simulation,revision:0,facts:[],sources:[],rules:[],custom_original:'',settings:{market:'US',language:'en-US+zh-CN',quantity:task.qa_count||5,question_max:20,answer_min:30,answer_max:60,measure:'英文词数',length_policy:'建议；简单回答可更短',tone:'自然美式英语，品牌说明口吻',audience:'',scenes:'',must_topics:'',forbidden:'无依据的绝对安全、效果保证；虚构买家经历',keywords:''},issues:[],events:[],facts_confirmation:null,rules_confirmation:null,accepted_gaps:[],invalidations:[]};}
function event(s,type,detail){s.events.push({id:id(),at:now(),type,...copy(detail)});s.revision++;}
function invalidate(s,kind,ids,reason){s[kind+'_confirmation']=null;s.invalidations.push({id:id(),at:now(),kind,ids:copy(ids),reason,downstream:'待对应阶段接入',review_required:true});}
function sourceProblems(s,f){const problems=[];if(f.provided_by==='用户提供'){if(!text(f.user_original))problems.push('缺用户提供原文');return problems;}
 const src=s.sources.find(x=>x.id===f.source_id);if(!src){problems.push('来源记录不存在');return problems;}
 if(src.kind!=='product'||src.relation!=='own')problems.push('来源不是自家产品资料，不能证明自家能力');
 if(src.product!==f.product)problems.push('来源产品与事实产品不符');
 if(!src.current)problems.push('来源已被替换，需重新核对');
 if(!text(f.quote)||!src.original.includes(f.quote))problems.push('原文引用不能回查');
 if(!same(f.source_version,src.version))problems.push('来源版本不符');
 return problems;
}
function factProblems(s,f){const p=sourceProblems(s,f);if(!text(f.product)||!text(f.variant)||f.variant==='未指定')p.push('需明确产品/变体，通用事实请填“通用”');if(f.product!==s.product)p.push('不适用当前目标产品');if(f.variant!=='通用'&&f.variant!==s.variant)p.push('不适用当前目标变体');if(!text(f.attribute)||!text(f.value))p.push('缺属性或值');if(!text(f.unit))p.push('单位未说明，无单位请填“不适用”');if(!text(f.conditions))p.push('条件未说明，无额外条件请明确填写');if(!f.original_reviewed)p.push('尚未逐项核对数值、单位和原文限定');
 const original=f.provided_by==='用户提供'?f.user_original:f.quote;
 for(const q of ['页面列示','最长','至少','最多','约','低档模式下'])if(String(original).includes(q)&&!(f.value+' '+f.conditions).includes(q))p.push('遗漏原文限定：'+q);
 const numbers=String(f.value).match(/\d+(?:\.\d+)?/g)||[];if(numbers.some(n=>!String(original).includes(n)))p.push('数值无法在引用原文中找到；修改数据请另补用户提供来源');
 if(!Array.isArray(f.qualifiers))p.push('缺原文限定清单');else for(const q of f.qualifiers){if(!text(q)||!String(original).includes(q))p.push('限定词无法回查原文');else if(!(f.value+' '+f.conditions).includes(q))p.push('遗漏原文限定：'+q);}
 return [...new Set(p)];}
function conflicts(s){const active=s.facts.filter(f=>f.status!=='暂不采用');const found=[];for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j];if(a.product!==b.product||a.attribute.trim()!==b.attribute.trim())continue;const overlap=a.variant===b.variant||a.variant==='通用'||b.variant==='通用';if(!overlap)continue;if(!same([a.value,a.unit,a.conditions],[b.value,b.unit,b.conditions]))found.push({key:[a.id,b.id].sort().join(':'),fact_ids:[a.id,b.id],kind:'同属性值或条件不一致',message:'请对照两条原文确认是否冲突；不自动选择值或换算单位。',critical:true,status:'待处理'});}return found;}
function refresh(s){const pairs=conflicts(s),ids=new Set(pairs.flatMap(p=>p.fact_ids));for(const f of s.facts){if(f.status==='暂不采用')continue;const problems=factProblems(s,f);if(ids.has(f.id)){if(f.status==='已确认')invalidate(s,'facts',[f.id],'新冲突影响已确认事实');f.status='有冲突';}else if(f.status==='有冲突')f.status='待确认';if(problems.length&&f.status==='已确认'){f.status='待确认';f.confirmed_at=null;invalidate(s,'facts',[f.id],'来源或核对要求变化');}}
 return pairs;}
function withChange(input,fn){const s=copy(input);fn(s);refresh(s);return s;}
function replaceSources(input,sources){return withChange(input,s=>{requireThat(Array.isArray(sources),'来源必须为数组');const previous=s.sources;s.sources=copy(sources);if(!same(previous,s.sources)){invalidate(s,'facts',s.facts.map(f=>f.id),'来源清单或版本变化');event(s,'sources_changed',{});}});}
function addFact(input,candidate){return withChange(input,s=>{const f={id:id(),version:1,product:s.product,variant:s.variant,attribute:'',value:'',unit:'',conditions:'',qualifiers:[],provided_by:'资料原文',source_id:null,source_version:null,quote:'',user_original:'',original_reviewed:false,status:'待确认',confirmed_at:null,history:[],...copy(candidate)};f.id=id();f.version=1;f.status='待确认';f.confirmed_at=null;f.history=[];requireThat(['资料原文','用户提供'].includes(f.provided_by),'来源类型无效');requireThat(sourceProblems(s,f).length===0,sourceProblems(s,f).join('；'));s.facts.push(f);invalidate(s,'facts',[f.id],'新增事实待确认');event(s,'fact_added',{fact_id:f.id});});}
function editFact(input,factId,patch,reason){return withChange(input,s=>{requireThat(text(reason),'请填写修改原因');const f=s.facts.find(x=>x.id===factId);requireThat(f,'事实不存在');const allowed=['product','variant','attribute','value','unit','conditions','qualifiers','original_reviewed'];requireThat(Object.keys(patch).every(k=>allowed.includes(k)),'原文和来源不可覆盖；补充资料请新增用户提供事实');const old=copy(f);delete old.history;f.history.push({previous:old,reason,at:now()});Object.assign(f,copy(patch));f.version++;f.status='待确认';f.confirmed_at=null;invalidate(s,'facts',[f.id],'修改事实：'+reason);event(s,'fact_edited',{fact_id:f.id,reason,version:f.version});});}
function excludeFact(input,factId,reason){return withChange(input,s=>{requireThat(text(reason),'请填写暂不采用原因');const f=s.facts.find(x=>x.id===factId);requireThat(f,'事实不存在');const old=copy(f);delete old.history;f.history.push({previous:old,reason,at:now()});f.version++;f.status='暂不采用';f.confirmed_at=null;invalidate(s,'facts',[f.id],'暂不采用：'+reason);event(s,'fact_excluded',{fact_id:f.id,reason});});}
function confirmSelected(input,selected){return withChange(input,s=>{requireThat(Array.isArray(selected)&&selected.length>0,'请明确勾选记录');const pairs=refresh(s),blocked=new Set(pairs.flatMap(x=>x.fact_ids));const targets=[...new Set(selected)].map(k=>s.facts.find(f=>f.id===k));requireThat(targets.every(Boolean),'选择包含不存在记录');for(const f of targets)requireThat(f.status!=='暂不采用'&&!blocked.has(f.id)&&factProblems(s,f).length===0,'选中事实仍有冲突或待补：'+f.attribute);for(const f of targets){const old=copy(f);delete old.history;f.history.push({previous:old,reason:'明确选择确认',at:now()});f.status='已确认';f.confirmed_at=now();f.version++;}s.facts_confirmation=null;event(s,'facts_confirmed',{fact_ids:selected});});}
function addGap(input,{message,critical=true,fact_ids=[],source_ids=[]}){return withChange(input,s=>{requireThat(text(message),'请说明待补项');s.issues.push({id:id(),message,critical:!!critical,fact_ids:copy(fact_ids),source_ids:copy(source_ids),status:'待处理',history:[]});invalidate(s,'facts',fact_ids,'新增待补');event(s,'gap_added',{message});});}
function resolveGap(input,gapId,action,reason){return withChange(input,s=>{requireThat(text(reason),'需说明处理理由');const gap=s.issues.find(x=>x.id===gapId);requireThat(gap,'待补不存在');requireThat(['已解决','接受非关键待补'].includes(action),'处理方式无效');requireThat(action!=='接受非关键待补'||!gap.critical,'关键问题不可直接接受');gap.history.push({from:gap.status,to:action,reason,at:now()});gap.status=action;gap.reason=reason;gap.resolved_at=now();invalidate(s,'facts',gap.fact_ids,'待补处理变化');event(s,'gap_resolved',{gap_id:gapId,action,reason});});}
function setSettings(input,patch){return withChange(input,s=>{requireThat(Object.keys(patch).every(k=>k in s.settings),'未知固定设置');const next={...s.settings,...copy(patch)};requireThat(next.market==='US'&&next.language==='en-US+zh-CN','本项目已确认美国站、英文附中文');requireThat(Number.isSafeInteger(next.quantity)&&next.quantity>0,'数量必须为正整数');requireThat(Number.isFinite(next.question_max)&&next.question_max>0&&Number.isFinite(next.answer_min)&&Number.isFinite(next.answer_max)&&next.answer_min>=0&&next.answer_max>=next.answer_min,'长度设置无效');requireThat(next.measure==='英文词数','当前计量方式为英文词数');s.settings=next;for(const rule of s.rules){rule.status='待确认';rule.confirmed_at=null;}invalidate(s,'rules',s.rules.map(x=>x.id),'固定设置变化');event(s,'settings_changed',{patch});});}
function setCustom(input,original){return withChange(input,s=>{requireThat(typeof original==='string','指令需为文字');s.custom_original=original;for(const r of s.rules){r.status='待确认';r.confirmed_at=null;r.stale=true;}invalidate(s,'rules',s.rules.map(r=>r.id),'指令原文变化');event(s,'custom_changed',{});});}
function addRule(input,c){return withChange(input,s=>{requireThat(text(c.original)&&s.custom_original.includes(c.original),'规则原文不在独立写作指令中');requireThat(['硬性要求','写作偏好','内容诉求'].includes(c.category),'规则类别无效');requireThat(text(c.understanding)&&text(c.check),'缺系统理解或检查方式');requireThat(Array.isArray(c.pending)&&Array.isArray(c.fact_ids),'待确认事项和事实依据需为数组');if(c.fixed_key)requireThat(c.fixed_key in s.settings,'固定字段不存在');const r={...copy(c),id:id(),version:1,status:'待确认',stale:false,confirmed_at:null,history:[]};s.rules.push(r);invalidate(s,'rules',[r.id],'新增规则');event(s,'rule_added',{rule_id:r.id});});}
function ruleProblems(s,r){const p=[];if(r.stale||!s.custom_original.includes(r.original))p.push('原始指令已变化，需重新解析');if(r.pending.length)p.push(...r.pending);if(r.fixed_key&&!same(s.settings[r.fixed_key],r.expected))p.push('与固定设置矛盾：'+r.fixed_key);if(r.category==='内容诉求'&&r.requires_fact!==false){if(!r.fact_ids.length)p.push('必讲内容缺事实依据');for(const fid of r.fact_ids){const f=s.facts.find(f=>f.id===fid);if(!f||f.status!=='已确认'||factProblems(s,f).length||conflicts(s).some(x=>x.fact_ids.includes(fid)))p.push('引用事实尚未有效确认');}}return [...new Set(p)];}
function editRule(input,rid,patch,reason){return withChange(input,s=>{requireThat(text(reason),'需填写解释或选择理由');const r=s.rules.find(x=>x.id===rid);requireThat(r,'规则不存在');requireThat(Object.keys(patch).every(k=>['understanding','check','pending','fact_ids','expected','fixed_key','category','requires_fact'].includes(k)),'原始要求不可覆盖');const old=copy(r);delete old.history;r.history.push({previous:old,reason,at:now()});Object.assign(r,copy(patch));r.version++;r.status='待确认';r.confirmed_at=null;invalidate(s,'rules',[rid],'规则修改');event(s,'rule_edited',{rule_id:rid,reason});});}
function decideRule(input,rid,use,reason){return withChange(input,s=>{const r=s.rules.find(x=>x.id===rid);requireThat(r,'规则不存在');requireThat(text(reason),'请填写确认或不采用理由');if(use)requireThat(ruleProblems(s,r).length===0,ruleProblems(s,r).join('；'));const old=copy(r);delete old.history;r.history.push({previous:old,reason,at:now()});r.status=use?'已确认':'暂不采用';r.confirmed_at=use?now():null;r.version++;invalidate(s,'rules',[rid],'规则确认选择');event(s,'rule_decided',{rule_id:rid,use,reason});});}
function setTarget(input,product,variant){return withChange(input,s=>{requireThat(text(product)&&text(variant)&&variant!=='未指定','请明确目标产品和变体');s.product=product;s.variant=variant;for(const f of s.facts){if(f.status==='已确认'){f.status='待确认';f.confirmed_at=null;}}invalidate(s,'facts',s.facts.map(f=>f.id),'目标产品或变体变更');invalidate(s,'rules',s.rules.map(r=>r.id),'目标产品或变体变更');event(s,'target_changed',{product,variant});});}
function problems(input){const s=copy(input),pairs=refresh(s);return {conflicts:pairs,facts:s.facts.filter(f=>f.status!=='暂不采用').map(f=>({id:f.id,problems:factProblems(s,f)})),rules:s.rules.filter(r=>r.status!=='暂不采用').map(r=>({id:r.id,problems:ruleProblems(s,r)})),gaps:s.issues.filter(g=>g.status==='待处理')};}
function factGate(s){const p=problems(s);const active=s.facts.filter(f=>f.status!=='暂不采用');return active.some(f=>f.status==='已确认')&&p.conflicts.length===0&&p.gaps.length===0&&active.every(f=>f.status==='已确认'&&factProblems(s,f).length===0);}
function ruleGate(s){const topics=(s.settings.must_topics||'').split(/\r?\n/).map(t=>t.trim()).filter(Boolean);if(topics.some(t=>!s.rules.some(r=>r.category==='内容诉求'&&r.status==='已确认'&&(r.original.includes(t)||r.understanding.includes(t))&&r.fact_ids.length>0&&ruleProblems(s,r).length===0)))return false;const remaining=s.custom_original.split(/\r?\n/).filter(x=>x.trim()).filter(line=>!s.rules.some(r=>!r.stale&&r.original.includes(line)));if(remaining.length)return false;return s.rules.every(r=>r.status==='暂不采用'||r.status==='已确认'&&ruleProblems(s,r).length===0)&&(!s.custom_original.trim()||s.rules.some(r=>!r.stale));}
function confirmSection(input,kind){return withChange(input,s=>{requireThat(['facts','rules'].includes(kind),'确认区域无效');requireThat(kind==='facts'?factGate(s):ruleGate(s),'该区域仍有未处理项');s[kind+'_confirmation']={at:now(),revision:s.revision,simulation:s.simulation};event(s,'section_confirmed',{kind});});}
function gate(s){const reasons=[];if(s.simulation)reasons.push('模拟数据仅供验证，不进入真实下一阶段');if(!s.facts_confirmation||!factGate(s))reasons.push('产品事实尚未完成有效确认');if(!s.rules_confirmation||!ruleGate(s))reasons.push('写作规则尚未完成有效确认');return {ready:!reasons.length,reasons,warnings:s.issues.filter(g=>g.status==='接受非关键待补').map(g=>g.message)};}
function bundle(input){const s=copy(input);refresh(s);return {'facts.json':{schema_version:1,task_id:s.task_id,revision:s.revision,simulation:s.simulation,product:s.product,variant:s.variant,facts:s.facts,sources:s.sources,confirmation:s.facts_confirmation,events:s.events,invalidations:s.invalidations},'fact_conflicts.json':{schema_version:1,task_id:s.task_id,revision:s.revision,conflicts:conflicts(s),validation:problems(s).facts,issues:s.issues},'writing_rules.json':{schema_version:1,task_id:s.task_id,revision:s.revision,simulation:s.simulation,settings:s.settings,original:s.custom_original,rules:s.rules,confirmation:s.rules_confirmation,gate:gate(s)}};}
const api={setTarget,blank,replaceSources,addFact,editFact,excludeFact,confirmSelected,addGap,resolveGap,setSettings,setCustom,addRule,editRule,decideRule,confirmSection,gate,bundle,problems,factProblems,ruleProblems,states};root.QAReviewCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
